

 const users = [`
    type User {
        id: ID!
        username: String!
        name: String
        email: String
    }

    type Query {
        users: [User]!
        # user: User!
    }
`]
module.exports = users

